import { describe, it, expect, afterEach } from 'vitest';
import { execa } from 'execa';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

// THE TERMINAL AND JSON CONTRACT, END TO END.
//
// The badge is generated by renderBadge and printed by the CLI's human path; a
// reviewer once saw a stale cached build and concluded the terminal renderer was
// broken. This suite runs the real CLI and asserts the generated badge actually
// reaches stdout, and that --json carries the reviewer's required fields
// (occurrence vs model counts, the two deadline fields, per-model verdicts).
//
// gpt-4-0613 is `verified` in the shipped registry, so a live `model:` argument
// classifies Tier A — an auto_fixable model, red badge.

const MENDR_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const created: string[] = [];
afterEach(() => {
  for (const dir of created.splice(0)) {
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best effort */
    }
  }
});

function repoWith(content: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'mendr-watch-stdout-'));
  created.push(dir);
  writeFileSync(join(dir, 'app.ts'), content);
  return dir;
}

async function runWatch(args: string[]): Promise<{ exitCode: number; stdout: string }> {
  const result = await execa('tsx', ['src/cli.ts', 'watch', ...args], {
    cwd: MENDR_ROOT,
    preferLocal: true,
    reject: false,
    windowsHide: true,
  });
  return { exitCode: result.exitCode ?? 0, stdout: result.stdout ?? '' };
}

const LIVE = 'export const c = create({ model: "gpt-4-0613" });\n';

describe('watch terminal + json output', () => {
  it(
    'prints the generated badge in the terminal (non-json)',
    async () => {
      const { stdout } = await runWatch([repoWith(LIVE), '--no-exposure-file']);
      expect(stdout).toContain('Optional README badge');
      expect(stdout).toMatch(/!\[mendr watch\]\(https:\/\/img\.shields\.io\/badge\/mendr-/);
      expect(stdout).toContain('gpt-4-0613');
    },
    120_000,
  );

  it(
    '--json carries occurrence + model counts, both deadline fields, and per-model verdicts',
    async () => {
      const { stdout } = await runWatch([repoWith(LIVE), '--no-exposure-file', '--json']);
      const j = JSON.parse(stdout) as {
        occurrenceCounts: { tierA: number; tierB: number; tierC: number };
        modelCounts: { reviewRequired: number; autoFixable: number; informational: number };
        nearestUpcomingDeadlineDays: number | null;
        mostOverdueDays: number | null;
        nearestDeadlineDays?: unknown;
        badge: string;
        models: Array<{
          disposition: string;
          replacementVerdict: string;
          autoApplyAllowed: boolean;
          locations: Array<{ tier: string; usageVerdict: string }>;
        }>;
      };
      // occurrence view vs model view are both present and distinct.
      expect(j.occurrenceCounts).toEqual({ tierA: 1, tierB: 0, tierC: 0 });
      expect(j.modelCounts).toEqual({ reviewRequired: 0, autoFixable: 1, informational: 0 });
      // the misleading single field is gone; the two clear ones are present.
      expect(j).not.toHaveProperty('nearestDeadlineDays');
      expect(j).toHaveProperty('nearestUpcomingDeadlineDays');
      expect(j).toHaveProperty('mostOverdueDays');
      // the badge in JSON matches what the terminal prints.
      expect(j.badge).toContain('https://img.shields.io/badge/mendr-');
      // per-model verification is preserved (a candidate is never read as verified).
      const m = j.models[0];
      expect(m.disposition).toBe('auto_fixable');
      expect(m.replacementVerdict).toBe('verified');
      expect(m.autoApplyAllowed).toBe(true);
      expect(m.locations[0].tier).toBe('A');
      expect(m.locations[0].usageVerdict).toBe('confirmed');
    },
    120_000,
  );
});
