// GENERATED by scripts/stamp-bundled-registry.mjs — do not edit by hand.
//
// When the registry bundled into THIS build was stamped as current (the
// release checklist runs the stamp right before tagging). The scanner grades
// the bundled registry's age from it, and refuses any downloaded snapshot
// published before it (rollback floor). See src/registry/freshRegistry.ts.

/** ISO-8601 UTC. */
export const BUNDLED_PUBLISHED_AT = '2026-10-07T04:33:06Z';
/** Content hash of registries/llm-deprecations.json at stamp time (informational). */
export const BUNDLED_REGISTRY_VERSION = 'sha256:4145ea23431d5bc5';
/** Entries in the bundled registry at stamp time (informational). */
export const BUNDLED_ENTRY_COUNT = 168;
