// GENERATED by scripts/stamp-bundled-registry.mjs — do not edit by hand.
//
// When the registry bundled into THIS build was stamped as current (the
// release checklist runs the stamp right before tagging). The scanner grades
// the bundled registry's age from it, and refuses any downloaded snapshot
// published before it (rollback floor). See src/registry/freshRegistry.ts.

/** ISO-8601 UTC. */
export const BUNDLED_PUBLISHED_AT = '2026-09-12T17:15:59Z';
/** Content hash of registries/llm-deprecations.json at stamp time (informational). */
export const BUNDLED_REGISTRY_VERSION = 'sha256:46cb77bc5e20c16f';
/** Entries in the bundled registry at stamp time (informational). */
export const BUNDLED_ENTRY_COUNT = 110;
